url: https://markvillar.github.io/
baseurl: 

# Site settings
title: The Living God Church
email: tlgcweb@tlg-church.com
description: "The Living God Church Website"

# Team names, titles and social links
people:
- name: Joseph Pascual
  pic: 1
  position: TLGC Senior Pastor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Jen Mendoze
  pic: 2
  position: TLGC London Pastor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Angelita Mamauag
  pic: 3
  position: TLGC Edinburgh Pastor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Romel Dano
  pic: 3
  position: TLGC Southampton Pastor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/tlgchurchuk
  - title: facebook
    url: https://www.facebook.com/TLGC777
  - title: stack-overflow
    url: #http://stackoverflow.com/questions/tagged/tlgc
  - title: bitbucket
    url: #http://bitbucket.org/tlgc
  - title: github
    url: #http://github.com/TLGC

# Postal address (add as many lines as necessary)
address:
  - line: St. Gabriel's Church
  - line: Tewkesbury Cl, Basingstoke RG24 9DU

# Build settings
markdown: kramdown
permalink: pretty
