url: https://markvillar.github.io/
baseurl:

# Site settings
title: The Living God Church
email: tlgcweb@tlg-church.com
description: "The Living God Church Website"

# pastors names, titles and social links
people:
- name: Joseph Pascual
  pic: p
  position: Senior Pastor - TLGC United Kingdom and Philippines
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Gen Mendoza
  pic: p
  position: Pastor - TLGC London
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Angie Mamauag
  pic: p
  position: Pastor - TLGC Edinburgh
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Neil Nobleza
  pic: p
  position: Associate Pastor - TLGC Edinburgh
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Bob Manlapaz
  pic: p
  position: Associate Pastor - TLGC Edinburgh
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Joseph Mamauag
  pic: p
  position: Associate Pastor - TLGC Edinburgh
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Sol Soriano
  pic: p
  position: Pastor - TLGC Glasgow
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Sam Sotes
  pic: p
  position: Pastor - TLGC Aberdeen
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Rowell Lalacsan
  pic: p
  position: Associate Pastor - TLGC Aberdeen
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Jomar Marcuap
  pic: p
  position: Pastor - TLGC Sariaya, Interim Pastor - TLGC Quezon City
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Braulio Tolentino
  pic: p
  position: Pastor - TLGC Camiling
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Romel Dano
  pic: p
  position: Pastor - TLGC Southampton
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Eugene Badilles
  pic: p
  position: Co-ordinator - Davao and Kidapawan Outreaches
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Edwin Badilles
  pic: p
  position: Co-ordinator - Davao and Kidapawan Outreaches
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/tlgchurchuk
  - title: facebook
    url: https://www.facebook.com/TLGC777
  - title: stack-overflow
    url: #http://stackoverflow.com/questions/tagged/tlgc
  - title: bitbucket
    url: #http://bitbucket.org/tlgc
  - title: github
    url: #http://github.com/TLGC

# Postal address (add as many lines as necessary)
address:
  - line: St. Gabriel's Church
  - line: Tewkesbury Cl, Basingstoke RG24 9DU

# Build settings
markdown: kramdown
permalink: pretty
